package com.maritime.dao;

import com.maritime.models.Academy;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface AcademyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.academy
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.academy
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int insert(Academy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.academy
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int insertSelective(Academy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.academy
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    Academy selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.academy
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int updateByPrimaryKeySelective(Academy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.academy
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int updateByPrimaryKey(Academy record);
}