package com.maritime.dao;

import com.maritime.models.Course;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

@Mapper
public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.course
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int deleteByPrimaryKey(Integer coid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.course
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int insert(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.course
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int insertSelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.course
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    Course selectByPrimaryKey(Integer coid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.course
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int updateByPrimaryKeySelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.course
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int updateByPrimaryKey(Course record);

    List<Course> selectForTeacher(Long coteacher1);

    List<Course> selectForStudent(Long psid);

    List<Course> selectForAdmin();

    List<Course> selectSelectiveCourse(String term);

    List<Course> selectSelectiveCourseFoStudent(@Param("sid")Long sid, @Param("term")String term);

    List<Course> selectCourseByTermForTeacher(Map<String, Object> params);

    List<Course> selectCourseByTermForAdmin(String[] term);
}