package com.maritime.dao;

import com.maritime.models.ListData;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ListDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.listdata
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int deleteByPrimaryKey(Integer ldid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.listdata
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int insert(ListData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.listdata
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int insertSelective(ListData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.listdata
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    ListData selectByPrimaryKey(Integer ldid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.listdata
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int updateByPrimaryKeySelective(ListData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.listdata
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int updateByPrimaryKey(ListData record);

    List<ListData> selectByListID(Integer ldlistid);
}