package com.maritime.dao;

import com.maritime.models.ListModel;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ListModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.list
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int deleteByPrimaryKey(Integer lsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.list
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int insert(ListModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.list
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int insertSelective(ListModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.list
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    ListModel selectByPrimaryKey(Integer lsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.list
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int updateByPrimaryKeySelective(ListModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.list
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int updateByPrimaryKey(ListModel record);
}