package com.maritime.dao;

import com.maritime.models.Schedule;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.schedule
     *
     * @mbggenerated Wed May 24 16:49:51 CST 2017
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.schedule
     *
     * @mbggenerated Wed May 24 16:49:51 CST 2017
     */
    int insert(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.schedule
     *
     * @mbggenerated Wed May 24 16:49:51 CST 2017
     */
    int insertSelective(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.schedule
     *
     * @mbggenerated Wed May 24 16:49:51 CST 2017
     */
    Schedule selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.schedule
     *
     * @mbggenerated Wed May 24 16:49:51 CST 2017
     */
    int updateByPrimaryKeySelective(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.schedule
     *
     * @mbggenerated Wed May 24 16:49:51 CST 2017
     */
    int updateByPrimaryKey(Schedule record);

    List<Schedule> selectForStudent(@Param("sid")Long sid, @Param("term")String term);

    List<Schedule> selectForTeacher(@Param("tid")Long tid, @Param("term")String term);

    int updateRemainPeople(@Param("sid")Integer sid, @Param("number")Integer number);
}