package com.maritime.dao;

import com.maritime.models.SCMapping;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SCMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.scmapping
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.scmapping
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int insert(SCMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.scmapping
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int insertSelective(SCMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.scmapping
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    SCMapping selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.scmapping
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int updateByPrimaryKeySelective(SCMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.scmapping
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int updateByPrimaryKey(SCMapping record);

    List<SCMapping> selectAllCourse(Long sid);

    List<SCMapping> selectAllCourseForTeacher(Long tid);

    List<SCMapping> selectAllTermsForStudent(Long sid);

    List<SCMapping> selectAllTermsForTeacher(Long tid);

    int inactiveScmapping(Integer[] pids);

    List<SCMapping> selectAllTermsForAdmin();
}