package com.maritime.dao;

import com.maritime.models.Student;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.student
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int deleteByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.student
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.student
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    //int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.student
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    Student selectByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.student
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    //int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.student
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int updateByPrimaryKey(Student record);

    Student selectByAccount(Long snumber);

    int updateForInfo(Student record);

    List<Student> selectForAll();

    int inactiveStudent(Long[] sids);

    List<Student> selectForDuplicate(Student student);
}