package com.maritime.dao;

import com.maritime.models.Teacher;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.teacher
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int deleteByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.teacher
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.teacher
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    Teacher selectByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.teacher
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    int updateByPrimaryKey(Teacher record);

    Teacher selectByAccount(Long tnumber);

    int updateForInfo(Teacher record);

    List<Teacher> selectForAll();
}