package com.maritime.models;

import java.util.Date;

public class Academy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.academy.aid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.academy.aname
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String aname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.academy.adescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String adescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.academy.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.academy.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String lastUpdateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.academy.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Date lastUpdateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.academy.aid
     *
     * @return the value of maritime.academy.aid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.academy.aid
     *
     * @param aid the value for maritime.academy.aid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.academy.aname
     *
     * @return the value of maritime.academy.aname
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.academy.aname
     *
     * @param aname the value for maritime.academy.aname
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.academy.adescription
     *
     * @return the value of maritime.academy.adescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getAdescription() {
        return adescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.academy.adescription
     *
     * @param adescription the value for maritime.academy.adescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setAdescription(String adescription) {
        this.adescription = adescription == null ? null : adescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.academy.is_active
     *
     * @return the value of maritime.academy.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.academy.is_active
     *
     * @param isActive the value for maritime.academy.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.academy.last_update_user
     *
     * @return the value of maritime.academy.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.academy.last_update_user
     *
     * @param lastUpdateUser the value for maritime.academy.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.academy.last_update_dt
     *
     * @return the value of maritime.academy.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.academy.last_update_dt
     *
     * @param lastUpdateDt the value for maritime.academy.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }
}