package com.maritime.models;

import java.util.Date;

public class Class {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.class.cid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.class.cnum
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer cnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.class.cmajor
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer cmajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.class.cyear
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer cyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.class.camount
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer camount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.class.cdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String cdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.class.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.class.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String lastUpdateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.class.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Date lastUpdateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.class.cid
     *
     * @return the value of maritime.class.cid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.class.cid
     *
     * @param cid the value for maritime.class.cid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.class.cnum
     *
     * @return the value of maritime.class.cnum
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getCnum() {
        return cnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.class.cnum
     *
     * @param cnum the value for maritime.class.cnum
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setCnum(Integer cnum) {
        this.cnum = cnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.class.cmajor
     *
     * @return the value of maritime.class.cmajor
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getCmajor() {
        return cmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.class.cmajor
     *
     * @param cmajor the value for maritime.class.cmajor
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setCmajor(Integer cmajor) {
        this.cmajor = cmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.class.cyear
     *
     * @return the value of maritime.class.cyear
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getCyear() {
        return cyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.class.cyear
     *
     * @param cyear the value for maritime.class.cyear
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setCyear(Integer cyear) {
        this.cyear = cyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.class.camount
     *
     * @return the value of maritime.class.camount
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getCamount() {
        return camount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.class.camount
     *
     * @param camount the value for maritime.class.camount
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setCamount(Integer camount) {
        this.camount = camount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.class.cdescription
     *
     * @return the value of maritime.class.cdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getCdescription() {
        return cdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.class.cdescription
     *
     * @param cdescription the value for maritime.class.cdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setCdescription(String cdescription) {
        this.cdescription = cdescription == null ? null : cdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.class.is_active
     *
     * @return the value of maritime.class.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.class.is_active
     *
     * @param isActive the value for maritime.class.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.class.last_update_user
     *
     * @return the value of maritime.class.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.class.last_update_user
     *
     * @param lastUpdateUser the value for maritime.class.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.class.last_update_dt
     *
     * @return the value of maritime.class.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.class.last_update_dt
     *
     * @param lastUpdateDt the value for maritime.class.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }
}