package com.maritime.models;

public class ListData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.listdata.ldid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer ldid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.listdata.ldlistid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer ldlistid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.listdata.ldvalue
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String ldvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.listdata.ldcode
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String ldcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.listdata.ldorder
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer ldorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.listdata.lddescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String lddescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.listdata.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.listdata.is_visible
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Boolean isVisible;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.listdata.ldid
     *
     * @return the value of maritime.listdata.ldid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getLdid() {
        return ldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.listdata.ldid
     *
     * @param ldid the value for maritime.listdata.ldid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLdid(Integer ldid) {
        this.ldid = ldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.listdata.ldlistid
     *
     * @return the value of maritime.listdata.ldlistid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getLdlistid() {
        return ldlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.listdata.ldlistid
     *
     * @param ldlistid the value for maritime.listdata.ldlistid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLdlistid(Integer ldlistid) {
        this.ldlistid = ldlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.listdata.ldvalue
     *
     * @return the value of maritime.listdata.ldvalue
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getLdvalue() {
        return ldvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.listdata.ldvalue
     *
     * @param ldvalue the value for maritime.listdata.ldvalue
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLdvalue(String ldvalue) {
        this.ldvalue = ldvalue == null ? null : ldvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.listdata.ldcode
     *
     * @return the value of maritime.listdata.ldcode
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getLdcode() {
        return ldcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.listdata.ldcode
     *
     * @param ldcode the value for maritime.listdata.ldcode
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLdcode(String ldcode) {
        this.ldcode = ldcode == null ? null : ldcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.listdata.ldorder
     *
     * @return the value of maritime.listdata.ldorder
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getLdorder() {
        return ldorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.listdata.ldorder
     *
     * @param ldorder the value for maritime.listdata.ldorder
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLdorder(Integer ldorder) {
        this.ldorder = ldorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.listdata.lddescription
     *
     * @return the value of maritime.listdata.lddescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getLddescription() {
        return lddescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.listdata.lddescription
     *
     * @param lddescription the value for maritime.listdata.lddescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLddescription(String lddescription) {
        this.lddescription = lddescription == null ? null : lddescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.listdata.is_active
     *
     * @return the value of maritime.listdata.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.listdata.is_active
     *
     * @param isActive the value for maritime.listdata.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.listdata.is_visible
     *
     * @return the value of maritime.listdata.is_visible
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Boolean getIsVisible() {
        return isVisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.listdata.is_visible
     *
     * @param isVisible the value for maritime.listdata.is_visible
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setIsVisible(Boolean isVisible) {
        this.isVisible = isVisible;
    }
}