package com.maritime.models;

public class ListModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.list.lsid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer lsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.list.lsname
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String lsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.list.lsdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String lsdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.list.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Boolean isActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.list.lsid
     *
     * @return the value of maritime.list.lsid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getLsid() {
        return lsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.list.lsid
     *
     * @param lsid the value for maritime.list.lsid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLsid(Integer lsid) {
        this.lsid = lsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.list.lsname
     *
     * @return the value of maritime.list.lsname
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getLsname() {
        return lsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.list.lsname
     *
     * @param lsname the value for maritime.list.lsname
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLsname(String lsname) {
        this.lsname = lsname == null ? null : lsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.list.lsdescription
     *
     * @return the value of maritime.list.lsdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getLsdescription() {
        return lsdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.list.lsdescription
     *
     * @param lsdescription the value for maritime.list.lsdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLsdescription(String lsdescription) {
        this.lsdescription = lsdescription == null ? null : lsdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.list.is_active
     *
     * @return the value of maritime.list.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.list.is_active
     *
     * @param isActive the value for maritime.list.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
}