package com.maritime.models;

import java.util.Date;

public class Major {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.major.mid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.major.mname
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String mname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.major.macademy
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer macademy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.major.mpointset
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer mpointset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.major.mdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String mdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.major.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.major.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String lastUpdateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.major.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Date lastUpdateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.major.mid
     *
     * @return the value of maritime.major.mid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.major.mid
     *
     * @param mid the value for maritime.major.mid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.major.mname
     *
     * @return the value of maritime.major.mname
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.major.mname
     *
     * @param mname the value for maritime.major.mname
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setMname(String mname) {
        this.mname = mname == null ? null : mname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.major.macademy
     *
     * @return the value of maritime.major.macademy
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getMacademy() {
        return macademy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.major.macademy
     *
     * @param macademy the value for maritime.major.macademy
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setMacademy(Integer macademy) {
        this.macademy = macademy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.major.mpointset
     *
     * @return the value of maritime.major.mpointset
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getMpointset() {
        return mpointset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.major.mpointset
     *
     * @param mpointset the value for maritime.major.mpointset
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setMpointset(Integer mpointset) {
        this.mpointset = mpointset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.major.mdescription
     *
     * @return the value of maritime.major.mdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getMdescription() {
        return mdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.major.mdescription
     *
     * @param mdescription the value for maritime.major.mdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setMdescription(String mdescription) {
        this.mdescription = mdescription == null ? null : mdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.major.is_active
     *
     * @return the value of maritime.major.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.major.is_active
     *
     * @param isActive the value for maritime.major.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.major.last_update_user
     *
     * @return the value of maritime.major.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.major.last_update_user
     *
     * @param lastUpdateUser the value for maritime.major.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.major.last_update_dt
     *
     * @return the value of maritime.major.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.major.last_update_dt
     *
     * @param lastUpdateDt the value for maritime.major.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }
}