package com.maritime.models;

import java.util.Date;

public class PointSet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.pointset.psid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer psid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.pointset.pssetid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer pssetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.pointset.pstotal
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Float pstotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.pointset.psmax
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Float psmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.pointset.psmin
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Float psmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.pointset.pscategory
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer pscategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.pointset.pstype
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer pstype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.pointset.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.pointset.psdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String psdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.pointset.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String lastUpdateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.pointset.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Date lastUpdateDt;

    private Float force;

    private Float limit;

    private Float alter;

    private Float curforce;

    private Float curlimit;

    private Float curalter1;

    private Float curalter2;

    private Float curalter3;

    private Float curalter4;

    private Long allcourse;

    private Float allcoursepoint;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.pointset.psid
     *
     * @return the value of maritime.pointset.psid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getPsid() {
        return psid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.pointset.psid
     *
     * @param psid the value for maritime.pointset.psid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setPsid(Integer psid) {
        this.psid = psid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.pointset.pssetid
     *
     * @return the value of maritime.pointset.pssetid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getPssetid() {
        return pssetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.pointset.pssetid
     *
     * @param pssetid the value for maritime.pointset.pssetid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setPssetid(Integer pssetid) {
        this.pssetid = pssetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.pointset.pstotal
     *
     * @return the value of maritime.pointset.pstotal
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Float getPstotal() {
        return pstotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.pointset.pstotal
     *
     * @param pstotal the value for maritime.pointset.pstotal
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setPstotal(Float pstotal) {
        this.pstotal = pstotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.pointset.psmax
     *
     * @return the value of maritime.pointset.psmax
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Float getPsmax() {
        return psmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.pointset.psmax
     *
     * @param psmax the value for maritime.pointset.psmax
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setPsmax(Float psmax) {
        this.psmax = psmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.pointset.psmin
     *
     * @return the value of maritime.pointset.psmin
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Float getPsmin() {
        return psmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.pointset.psmin
     *
     * @param psmin the value for maritime.pointset.psmin
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setPsmin(Float psmin) {
        this.psmin = psmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.pointset.pscategory
     *
     * @return the value of maritime.pointset.pscategory
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getPscategory() {
        return pscategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.pointset.pscategory
     *
     * @param pscategory the value for maritime.pointset.pscategory
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setPscategory(Integer pscategory) {
        this.pscategory = pscategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.pointset.pstype
     *
     * @return the value of maritime.pointset.pstype
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getPstype() {
        return pstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.pointset.pstype
     *
     * @param pstype the value for maritime.pointset.pstype
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setPstype(Integer pstype) {
        this.pstype = pstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.pointset.is_active
     *
     * @return the value of maritime.pointset.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.pointset.is_active
     *
     * @param isActive the value for maritime.pointset.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.pointset.psdescription
     *
     * @return the value of maritime.pointset.psdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getPsdescription() {
        return psdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.pointset.psdescription
     *
     * @param psdescription the value for maritime.pointset.psdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setPsdescription(String psdescription) {
        this.psdescription = psdescription == null ? null : psdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.pointset.last_update_user
     *
     * @return the value of maritime.pointset.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.pointset.last_update_user
     *
     * @param lastUpdateUser the value for maritime.pointset.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.pointset.last_update_dt
     *
     * @return the value of maritime.pointset.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.pointset.last_update_dt
     *
     * @param lastUpdateDt the value for maritime.pointset.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }

    public Float getForce() {
        return force;
    }

    public void setForce(Float force) {
        this.force = force;
    }

    public Float getAlter() {
        return alter;
    }

    public void setAlter(Float alter) {
        this.alter = alter;
    }

    public Float getLimit() {
        return limit;
    }

    public void setLimit(Float limit) {
        this.limit = limit;
    }

    public Float getCurforce() {
        return curforce;
    }

    public void setCurforce(Float curforce) {
        this.curforce = curforce;
    }

    public Float getCurlimit() {
        return curlimit;
    }

    public void setCurlimit(Float curlimit) {
        this.curlimit = curlimit;
    }

    public Float getCuralter1() {
        return curalter1;
    }

    public void setCuralter1(Float curalter1) {
        this.curalter1 = curalter1;
    }

    public Float getCuralter2() {
        return curalter2;
    }

    public void setCuralter2(Float curalter2) {
        this.curalter2 = curalter2;
    }

    public Float getCuralter3() {
        return curalter3;
    }

    public void setCuralter3(Float curalter3) {
        this.curalter3 = curalter3;
    }

    public Float getCuralter4() {
        return curalter4;
    }

    public void setCuralter4(Float curalter4) {
        this.curalter4 = curalter4;
    }

    public Long getAllcourse() {
        return allcourse;
    }

    public void setAllcourse(Long allcourse) {
        this.allcourse = allcourse;
    }

    public Float getAllcoursepoint() {
        return allcoursepoint;
    }

    public void setAllcoursepoint(Float allcoursepoint) {
        this.allcoursepoint = allcoursepoint;
    }
}