package com.maritime.models;

import java.util.Date;

public class SCMapping {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.scmapping.pid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.scmapping.pcid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer pcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.scmapping.psid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer psid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.scmapping.start_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Date startDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.scmapping.finish_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Date finishDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.scmapping.pterm
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String pterm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.scmapping.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.scmapping.pdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String pdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.scmapping.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String lastUpdateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.scmapping.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Date lastUpdateDt;

    private String course;

    private Long cnumber;

    private String teacher;

    private String academy;

    private String category;

    private String type;

    private Float point;

    private Integer hour;

    private String examtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.scmapping.pid
     *
     * @return the value of maritime.scmapping.pid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.scmapping.pid
     *
     * @param pid the value for maritime.scmapping.pid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.scmapping.pcid
     *
     * @return the value of maritime.scmapping.pcid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getPcid() {
        return pcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.scmapping.pcid
     *
     * @param pcid the value for maritime.scmapping.pcid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setPcid(Integer pcid) {
        this.pcid = pcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.scmapping.psid
     *
     * @return the value of maritime.scmapping.psid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getPsid() {
        return psid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.scmapping.psid
     *
     * @param psid the value for maritime.scmapping.psid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setPsid(Integer psid) {
        this.psid = psid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.scmapping.start_dt
     *
     * @return the value of maritime.scmapping.start_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Date getStartDt() {
        return startDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.scmapping.start_dt
     *
     * @param startDt the value for maritime.scmapping.start_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setStartDt(Date startDt) {
        this.startDt = startDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.scmapping.finish_dt
     *
     * @return the value of maritime.scmapping.finish_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Date getFinishDt() {
        return finishDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.scmapping.finish_dt
     *
     * @param finishDt the value for maritime.scmapping.finish_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setFinishDt(Date finishDt) {
        this.finishDt = finishDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.scmapping.pterm
     *
     * @return the value of maritime.scmapping.pterm
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getPterm() {
        return pterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.scmapping.pterm
     *
     * @param pterm the value for maritime.scmapping.pterm
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setPterm(String pterm) {
        this.pterm = pterm == null ? null : pterm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.scmapping.is_active
     *
     * @return the value of maritime.scmapping.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.scmapping.is_active
     *
     * @param isActive the value for maritime.scmapping.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.scmapping.pdescription
     *
     * @return the value of maritime.scmapping.pdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getPdescription() {
        return pdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.scmapping.pdescription
     *
     * @param pdescription the value for maritime.scmapping.pdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setPdescription(String pdescription) {
        this.pdescription = pdescription == null ? null : pdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.scmapping.last_update_user
     *
     * @return the value of maritime.scmapping.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.scmapping.last_update_user
     *
     * @param lastUpdateUser the value for maritime.scmapping.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.scmapping.last_update_dt
     *
     * @return the value of maritime.scmapping.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.scmapping.last_update_dt
     *
     * @param lastUpdateDt the value for maritime.scmapping.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }

    public String getCourse() {
        return course;
    }

    public void setCourse(String course) {
        this.course = course;
    }

    public Long getCnumber() {
        return cnumber;
    }

    public void setCnumber(Long cnumber) {
        this.cnumber = cnumber;
    }

    public String getTeacher() {
        return teacher;
    }

    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }

    public String getAcademy() {
        return academy;
    }

    public void setAcademy(String academy) {
        this.academy = academy;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Float getPoint() {
        return point;
    }

    public void setPoint(Float point) {
        this.point = point;
    }

    public Integer getHour() {
        return hour;
    }

    public void setHour(Integer hour) {
        this.hour = hour;
    }

    public String getExamtype() {
        return examtype;
    }

    public void setExamtype(String examtype) {
        this.examtype = examtype;
    }
}