package com.maritime.models;

import java.util.Date;

public class Score {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.score.sid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.score.seid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer seid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.score.ssid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer ssid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.score.score
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.score.point
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Float point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.score.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.score.sdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String sdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.score.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String lastUpdateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.score.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Date lastUpdateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.score.sid
     *
     * @return the value of maritime.score.sid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.score.sid
     *
     * @param sid the value for maritime.score.sid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.score.seid
     *
     * @return the value of maritime.score.seid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getSeid() {
        return seid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.score.seid
     *
     * @param seid the value for maritime.score.seid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setSeid(Integer seid) {
        this.seid = seid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.score.ssid
     *
     * @return the value of maritime.score.ssid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getSsid() {
        return ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.score.ssid
     *
     * @param ssid the value for maritime.score.ssid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setSsid(Integer ssid) {
        this.ssid = ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.score.score
     *
     * @return the value of maritime.score.score
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.score.score
     *
     * @param score the value for maritime.score.score
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.score.point
     *
     * @return the value of maritime.score.point
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Float getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.score.point
     *
     * @param point the value for maritime.score.point
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setPoint(Float point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.score.is_active
     *
     * @return the value of maritime.score.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.score.is_active
     *
     * @param isActive the value for maritime.score.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.score.sdescription
     *
     * @return the value of maritime.score.sdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getSdescription() {
        return sdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.score.sdescription
     *
     * @param sdescription the value for maritime.score.sdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setSdescription(String sdescription) {
        this.sdescription = sdescription == null ? null : sdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.score.last_update_user
     *
     * @return the value of maritime.score.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.score.last_update_user
     *
     * @param lastUpdateUser the value for maritime.score.last_update_user
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.score.last_update_dt
     *
     * @return the value of maritime.score.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.score.last_update_dt
     *
     * @param lastUpdateDt the value for maritime.score.last_update_dt
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }
}