package com.maritime.models;

public class Student extends BaseModel{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.student.sid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.student.sname
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.student.ssex
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String ssex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.student.snumber
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Long snumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.student.spassword
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String spassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.student.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.student.stype
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer stype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.student.sdate
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String sdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.student.sacademy
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer sacademy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.student.smajor
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer smajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.student.sclass
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private Integer sclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maritime.student.sdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    private String sdescription;

    private String studenttype;

    private String academy;

    private String major;

    private Integer studentclass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.student.sid
     *
     * @return the value of maritime.student.sid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.student.sid
     *
     * @param sid the value for maritime.student.sid
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.student.sname
     *
     * @return the value of maritime.student.sname
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.student.sname
     *
     * @param sname the value for maritime.student.sname
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.student.ssex
     *
     * @return the value of maritime.student.ssex
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getSsex() {
        return ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.student.ssex
     *
     * @param ssex the value for maritime.student.ssex
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setSsex(String ssex) {
        this.ssex = ssex == null ? null : ssex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.student.snumber
     *
     * @return the value of maritime.student.snumber
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Long getSnumber() {
        return snumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.student.snumber
     *
     * @param snumber the value for maritime.student.snumber
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setSnumber(Long snumber) {
        this.snumber = snumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.student.spassword
     *
     * @return the value of maritime.student.spassword
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getSpassword() {
        return spassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.student.spassword
     *
     * @param spassword the value for maritime.student.spassword
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setSpassword(String spassword) {
        this.spassword = spassword == null ? null : spassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.student.is_active
     *
     * @return the value of maritime.student.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.student.is_active
     *
     * @param isActive the value for maritime.student.is_active
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.student.stype
     *
     * @return the value of maritime.student.stype
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getStype() {
        return stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.student.stype
     *
     * @param stype the value for maritime.student.stype
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setStype(Integer stype) {
        this.stype = stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.student.sdate
     *
     * @return the value of maritime.student.sdate
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.student.sdate
     *
     * @param sdate the value for maritime.student.sdate
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setSdate(String sdate) {
        this.sdate = sdate == null ? null : sdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.student.sacademy
     *
     * @return the value of maritime.student.sacademy
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getSacademy() {
        return sacademy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.student.sacademy
     *
     * @param sacademy the value for maritime.student.sacademy
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setSacademy(Integer sacademy) {
        this.sacademy = sacademy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.student.smajor
     *
     * @return the value of maritime.student.smajor
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getSmajor() {
        return smajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.student.smajor
     *
     * @param smajor the value for maritime.student.smajor
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setSmajor(Integer smajor) {
        this.smajor = smajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.student.sclass
     *
     * @return the value of maritime.student.sclass
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public Integer getSclass() {
        return sclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.student.sclass
     *
     * @param sclass the value for maritime.student.sclass
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setSclass(Integer sclass) {
        this.sclass = sclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maritime.student.sdescription
     *
     * @return the value of maritime.student.sdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public String getSdescription() {
        return sdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maritime.student.sdescription
     *
     * @param sdescription the value for maritime.student.sdescription
     *
     * @mbggenerated Wed Apr 19 22:55:14 CST 2017
     */
    public void setSdescription(String sdescription) {
        this.sdescription = sdescription == null ? null : sdescription.trim();
    }

    public String getStudenttype() {
        return studenttype;
    }

    public void setStudenttype(String studenttype) {
        this.studenttype = studenttype;
    }

    public String getAcademy() {
        return academy;
    }

    public void setAcademy(String academy) {
        this.academy = academy;
    }

    public String getMajor() {
        return major;
    }

    public void setMajor(String major) {
        this.major = major;
    }

    public Integer getStudentclass() {
        return studentclass;
    }

    public void setStudentclass(Integer studentclass) {
        this.studentclass = studentclass;
    }
}