package com.maritime.dao.mappers;

import com.maritime.models.TeacherModel;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TeacherModelMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.teacher
     *
     * @mbggenerated Mon Apr 17 23:47:28 CST 2017
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.teacher
     *
     * @mbggenerated Mon Apr 17 23:47:28 CST 2017
     */
    int insert(TeacherModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.teacher
     *
     * @mbggenerated Mon Apr 17 23:47:28 CST 2017
     */
    int insertSelective(TeacherModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.teacher
     *
     * @mbggenerated Mon Apr 17 23:47:28 CST 2017
     */
    TeacherModel selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.teacher
     *
     * @mbggenerated Mon Apr 17 23:47:28 CST 2017
     */
    int updateByPrimaryKeySelective(TeacherModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maritime.teacher
     *
     * @mbggenerated Mon Apr 17 23:47:28 CST 2017
     */
    int updateByPrimaryKey(TeacherModel record);
}